### ISSUE TITLE
getServiceSetting does not coerce value to boolean

### ISSUE THREAD

**Issue by GavinMendelGleason** [GavinMendelGleason/dacura#1]
On line 379 of dacura/dacura-web/phplib/services/config/Ontology.php there is a failure to type coerce a setting which may be set in the configuration page and therefore may be a string.  I see a number of other getServiceSettings that also do not coerce at the point that they are used.  

Is coercion supposed to occur at the point of input in the configuration?  If so, how is the interface to know of what type to coerce to?  If not, when do we coerce? 

This is a problem because the violation checker will always fail regardless of the setting in fail_on_ontology_hijack as it's a string (and therefore true).

~~~php5
  if(count($violations) > 0 && $srvr->getServiceSetting("fail_on_ontology_hijack", false)){
    $ores->errors = array_merge($ores->errors, $violations);
    return $ores->failure(400, "Ontology Hijacking identified in ontology", count($violations) . " instances detected and service setting: ");                                      
  }
~~~

**Comment by GavinMendelGleason** [comment]
Patched to read:

~~~php5
  $fail_setting = $srvr->getServiceSetting("fail_on_ontology_hijack", false);
  $fail_on_ontology_hijack = $srvr->getServiceSetting("fail_on_ontology_hijack", false) == "false" ? false : $fail_setting;
  if(count($violations) > 0 && $fail_on_ontology_hijack){

~~~

Not a permanent solution, but needed something working for now.

**Comment by kevinchekovfeeney** [comment]
The bug is really that I haven't written the config interfaces for these things - there's a setting in the settings that maps a setting to a form element, if none is defined it defaults to string.  The workaround is to use 0 as the string value.

**Comment by kevinchekovfeeney** [comment]
Fix is to add a line to config_form_fields in ld_settings.php which will go something like: 
			"fail_on_ontology_hijack" => array("label" => "Forbid Ontology Hijack", "type" => "boolean", "help" => "yada yada yada"),
